title: Apex Flow Toolhead Assembly Instructions
description: This is the official documentation for the Apex Flow toolhead.
theme: just-the-docs

url: https://apexinvent.github.io/ApexFlow-Toolhead-Documentation/

markdown: kramdown
remote_theme: just-the-docs/just-the-docs

logo: "/assets/apex_invent_logo.png"

favicon_ico: "/assets/apex_invent_icon.ico"

search_enabled: false
aux_links:
  Website: https://apexinvent.co.za/

aux_links_new_tab: true

color_scheme: apex_dark

